# Generated by Django 4.2.4 on 2023-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank='True', null='True', upload_to='blog/', verbose_name='превью'),
        ),
    ]
