# Generated by Django 4.2.4 on 2023-09-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_options_alter_blog_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('content_manager', 'can published, update, delete in blog')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
