# Generated by Django 4.2.4 on 2023-08-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_changing',
            new_name='changed_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_creation',
            new_name='created_at',
        ),
    ]
