# Generated by Django 4.2.4 on 2023-08-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
