# Generated by Django 4.2.4 on 2023-08-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_companycontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='icon',
        ),
        migrations.AddField(
            model_name='companycontact',
            name='icon_bootstrap',
            field=models.CharField(default='icon', max_length=100, verbose_name='Иконка Bootstrap'),
            preserve_default=False,
        ),
    ]
