# Generated by Django 4.2.4 on 2023-08-09 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_companycontact_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='changed_at',
            field=models.DateField(default=datetime.date(2023, 8, 10), verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 8, 10), verbose_name='Дата создания'),
        ),
    ]
