# Generated by Django 4.2.4 on 2023-08-16 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_changed_at_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('created_at', models.DateField(default=datetime.date(2023, 8, 16), verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Вопрос пользователя',
                'verbose_name_plural': 'Вопросы пользователей',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='changed_at',
            field=models.DateField(default=datetime.date(2023, 8, 16), verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 8, 16), verbose_name='Дата создания'),
        ),
    ]
