# Generated by Django 4.2.4 on 2023-08-19 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_changed_at_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='changed_at',
            field=models.DateField(default=datetime.date(2023, 8, 19), verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 8, 19), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 8, 19), verbose_name='Дата'),
        ),
    ]
