# Generated by Django 4.2.4 on 2023-08-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_changed_at_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_number', models.IntegerField(verbose_name='Номер')),
                ('harvest_date', models.DateField(verbose_name='Дата сбора урожая')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущая поставка (да/нет)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Сбор урожая',
                'verbose_name_plural': 'Сбор урожая',
            },
        ),
    ]
