# Generated by Django 4.2.4 on 2023-08-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_harvest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
    ]
